[package]
name = "project4"
version = "0.1.0"
edition = "2021"

[profile.release]
lto = true
codegen-units = 1
opt-level = 'z'
debug = false
strip = true
panic = "abort"

[dependencies]
colored = "2.1.0"
